In [66]:
import numpy as np

## Broadcasting

Broadcasting automatically expands smaller array to same length as bigger array.

In [67]:
m = np.array([1,2,3])
n = np.array([4])

print(m+n)

[5 6 7]


In [68]:
m = np.array([[1, 2, 3], [4, 5, 6]])
n = np.array([10, 20, 30])

print(m+n)

[[11 22 33]
 [14 25 36]]


In [69]:
m = np.array([[1, 2, 3], [4, 5, 6]])
n = np.array([[10], [20]])

print(m+n)

[[11 12 13]
 [24 25 26]]


In [70]:
m = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
n = np.array([10, 20, 30])

print(m+n)

[[[11 22 33]
  [14 25 36]]

 [[17 28 39]
  [20 31 42]]]


## Advanced Indexing

Basic indexing

In [71]:
m = np.array([1,4,112,6,5,17,3])

print(m[0])

print('1------------------')

print(m[0:3])

print('2------------------')

print(m[0:5:2])

1
1------------------
[  1   4 112]
2------------------
[  1 112   5]


In [72]:
m = np.array([[1,4,112], [6,5,17], [3,45,1234]])

print(m[2][2])

print('1------------------')

print(m[1:2])

1234
1------------------
[[ 6  5 17]]


Dimensional indexing

In [73]:
m = np.array([[1,4,112], [6,5,17], [3,45,1234]])

print(m[:, :])

print('1------------------')

print(m[2, :])

print('2------------------')

print(m[:, 2])

print('3------------------')

print(m[:, 1, np.newaxis])

print('4------------------')

print(m[np.newaxis, 1])

[[   1    4  112]
 [   6    5   17]
 [   3   45 1234]]
1------------------
[   3   45 1234]
2------------------
[ 112   17 1234]
3------------------
[[ 4]
 [ 5]
 [45]]
4------------------
[[ 6  5 17]]


Advanced indexing

In [74]:
m = np.array([[1,4,112], [6,5,17], [3,45,1234]])

print(m[:, [0,2]])

print('1------------------')

print(m[[0,2], [0,2]])

print('2------------------')

print(m[[0, 1, 2], [0, 1, 2]])

[[   1  112]
 [   6   17]
 [   3 1234]]
1------------------
[   1 1234]
2------------------
[   1    5 1234]


In [75]:
m = np.array([[1,4,112], [6,5,17], [3,45,1234]])

print(m[[True, False, True]])

print('1------------------')

print(m[[[True, True, True], [True, False, True], [True, True, True]]])

[[   1    4  112]
 [   3   45 1234]]
1------------------
[   1    4  112    6   17    3   45 1234]


## Sorting & Searching

### Sorting

The key difference is that np.sort(m) returns a copy of the sorted array, leaving the original array m unchanged, whereas m.sort() modifies the array in-place and returns None.

In [76]:
m = np.array([[5,9,8], [4,1,61], [7,3,211]])

print(np.sort(m, axis= 1))

print('1------------------')
      
print(np.sort(m, axis= 0))

print('2------------------')

print(np.sort(np.sort(m, axis= 0), axis= 1))

print('3------------------')

print(np.sort(m.flatten().reshape(m.shape)))

print('4------------------')

n= m.sort()

print(n)

[[  5   8   9]
 [  1   4  61]
 [  3   7 211]]
1------------------
[[  4   1   8]
 [  5   3  61]
 [  7   9 211]]
2------------------
[[  1   4   8]
 [  3   5  61]
 [  7   9 211]]
3------------------
[[  5   8   9]
 [  1   4  61]
 [  3   7 211]]
4------------------
None


### Searching

In [86]:
m = np. array([0.05, 0.01, 0.87, 0.02, 0.01, 0.03, 0, 0.011])

print(np.argmax(m))
print(np.argmin(m))

print('1------------------')

print(np.nonzero(m))

print('2------------------')

print(np.where(m>0.01, m, 0))







2
6
1------------------
(array([0, 1, 2, 3, 4, 5, 7]),)
2------------------
[0.05  0.    0.87  0.02  0.    0.03  0.    0.011]


## Iterating

In [98]:
m = np.arange(24).reshape(3, 4, 2)

for row in m:
    for element in row:
        print(element , end= ' ')

print('\n1------------------')

for element in np.nditer(m):
    print(element , end= ' ')

print('\n2------------------')

with np.nditer(m, op_flags= ['readwrite']) as it :
    for element in it:
        element[...] = element ** 2

print(m)        


[0 1] [2 3] [4 5] [6 7] [8 9] [10 11] [12 13] [14 15] [16 17] [18 19] [20 21] [22 23] 
1------------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
2------------------
[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]]

 [[ 64  81]
  [100 121]
  [144 169]
  [196 225]]

 [[256 289]
  [324 361]
  [400 441]
  [484 529]]]
